### ISSUE TITLE
iOS build fails when trying to compile on physical device

### ISSUE THREAD

**Issue by chris24elias** [florindumitru/react-native-sip#3]
Hey there,

Whenever i try compiling for my physical device, i run into the error "Please specify target machine."

I've research and tried several things but no luck, any help would be much appreciated

Thanks

**Comment by jbro-io** [comment]
@chris24elias How did you solve this? I'm running into the same issue now.

**Comment by tuna1207** [comment]
Hi @chris24elias @jbroquist , is there any solution for this ? i'm also having the same problem.

**Comment by tuna1207** [comment]
Hmm i just updated to 2.8.8 and got a different error this time
```
'VialerPJSIP/pjsua.h' file not found
```
not sure why the maintainer removed post install step ( which download and build the vialerpjsip package ) in new version

**Comment by jbro-io** [comment]
@tunguyenbhtech I switched over to the react-native-pjsip library and was able to get that working.

**Comment by oojikoo** [comment]
I think it fails to build since this fix.  @florindumitru which rn version is working? I've tried with `0.61.4`. it didn't work.

**Comment by oojikoo** [comment]
@jbroquist which version of react-native-pjsip worked?  I tried pjsip but still failed to build on Physical devices.

**Comment by tuna1207** [comment]
@jbroquist @oojikoo newest version of this library v2.9.0 is working but you need docker installed on your machine, it takes quite some time to install the library and also when building sometimes i'm getting weird cyclic dependency errors but it goes away after several clean build folders and rebuild project.

**Comment by oojikoo** [comment]
@tunguyenbhtech thank you for the reply! I have docker install on my machine? why do I need docker for react native library? is there a link for a reference?

**Comment by tuna1207** [comment]
@oojikoo no problem, it's being used in react native pjsip builder, which this library download and run in libs.sh
https://github.com/florindumitru/react-native-pjsip-builder/blob/master/build_ios.sh

**Comment by oojikoo** [comment]
@tunguyenbhtech wow! thank you, man!  you saved my day!!

**Comment by oojikoo** [comment]
@tunguyenbhtech  how did you mange to make it work? what should I do after build?
I tried copying it to /node_modules/react-native-sip/ios to replace the original one. 
and /ios/pod install. but it failed.

**Comment by tuna1207** [comment]
@oojikoo what error are you having ?, after installing the library, i also just did normal `pod install` in ios folder.
also, i'm not sure what you mean by this step
```
copying it to /node_modules/react-native-sip/ios to replace the original one
```

**Comment by oojikoo** [comment]
@tunguyenbhtech oh you just added this library and run the project as below. and it worked, right? 
```
$ yarn add react-native-sip
$ cd ios; pod install; cd ..;
$ react native run-ios
```

in my case, this way didn't work.  so I tried copying it
```
$  cd react-native-pjsip-builder
$ ./build_ios.sh
$ copy -r dist/ios/VialerPJSIP.framework ../myproject/node_module/react-native-sip
```

I know the latest version of react-native-sip use `VialerPJSIP.framework` to build libraries. 
but it didn't work...

I'm getting something like this
```
fatal error: could not build module 'Darwin'
#include <stdbool.h>
 ~~~~~~~~^
1 error generated.
While building module 'UIKit' imported from /Users/nainxo13/Work/Atlaslabs/Dev/projects/switch/SwitchMobile/ios/Pods/Target Support Files/react-native-sip/react-native-sip-prefix.pch:2:
While building module 'QuartzCore' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIView.h:10:
In file included from <module-includes>:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/QuartzCore.h:9:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CoreAnimation.h:9:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CABase.h:11:10: fatal error: could not build module 'Darwin'
#include <stdbool.h>
```

I'm using
```
"react": "16.9.0",
"react-native": "0.61.4",
```

env is 
```
OS X : 10.15.2(Katalina)
Xcode: 11.3
```

**Comment by tuna1207** [comment]
@oojikoo ah right, that's the error i was talking about
```
when building sometimes i'm getting weird cyclic dependency errors but it goes away after several clean build folders and rebuild project.
```
you should try using xcode and clean build folder then rebuild several times

**Comment by oojikoo** [comment]
@tunguyenbhtech oh, the same error? so It's not just me 😌 
I usually use this https://github.com/pmadruga/react-native-clean-project to clean the project. 
I will definitely try xcode clean build!

**Comment by tuna1207** [comment]
> @tunguyenbhtech oh you just added this library and run the project as below. and it worked, right?
> 
> ```
> $ yarn add react-native-sip
> $ cd ios; pod install; cd ..;
> $ react native run-ios
> ```
> 
> in my case, this way didn't work. so I tried copying it
> 
> ```
> $  cd react-native-pjsip-builder
> $ ./build_ios.sh
> $ copy -r dist/ios/VialerPJSIP.framework ../myproject/node_module/react-native-sip
> ```
> 
> I know the latest version of react-native-sip use `VialerPJSIP.framework` to build libraries.
> but it didn't work...
> 
> I'm getting something like this
> 
> ```
> fatal error: could not build module 'Darwin'
> #include <stdbool.h>
>  ~~~~~~~~^
> 1 error generated.
> While building module 'UIKit' imported from /Users/nainxo13/Work/Atlaslabs/Dev/projects/switch/SwitchMobile/ios/Pods/Target Support Files/react-native-sip/react-native-sip-prefix.pch:2:
> While building module 'QuartzCore' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIView.h:10:
> In file included from <module-includes>:1:
> In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/QuartzCore.h:9:
> In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CoreAnimation.h:9:
> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CABase.h:11:10: fatal error: could not build module 'Darwin'
> #include <stdbool.h>
> ```
> 
> I'm using
> 
> ```
> "react": "16.9.0",
> "react-native": "0.61.4",
> ```
> 
> env is
> 
> ```
> OS X : 10.15.2(Katalina)
> Xcode: 11.3
> ```

@florindumitru do you know what could have caused the cyclic dependency error in here ?

**Comment by oojikoo** [comment]
![image](https://user-images.githubusercontent.com/10041686/71568847-ade11500-2b0d-11ea-8545-a5abc3f84230.png)

@tunguyenbhtech I guess the error you had was this one? after uninstalling & reinstalling XCode, now Im get the same as you did.

**Comment by tuna1207** [comment]
@oojikoo yes, that's the one.
It goes away after several clean build folder and rebuild again.

**Comment by oojikoo** [comment]
@tunguyenbhtech it didn't go away after lots of clean and build..
anything else you did?

**Comment by tuna1207** [comment]
@oojikoo right, that's weird, it's also happening on my coworker's machine but not on mine, i'm not sure what's missing.

**Comment by oojikoo** [comment]
@tunguyenbhtech I solved this! 
https://github.com/florindumitru/react-native-sip/issues/6#issuecomment-575955613

**Comment by tuna1207** [comment]
Great @oojikoo 👍

**Comment by romreed** [comment]
@tunguyenbhtech @oojikoo  can someone share working project?
